configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stainless-commons%2Frollin-7bcca4488c625ade3f4de4d4c2ecedbda347d11ce79e9146eaffa0f76142c1e4.yml
openapi_spec_hash: 0a4ee54cf9bdf485a9763c82110dfdda
config_hash: e3fcd81f3932d7df05c2524108bc7f20
